### ISSUE TITLE
When requested the Admin API - Kong falls

### ISSUE THREAD

**Issue by Nicerton** [Kong/kong-plugin-serverless-functions#19]
When the Lua function inside the plugin is called that performs a request to Kong's Admin API (like http://kong:8001/services/), the kong server stops responding on any port. Only restarting helps.
Is it possible to somehow make it possible to access api from the Lua function from the serverless plugin?
What is more, a request to any other third-party api receives an instant response.
Attach code:

myfunction = function()
  local http = require("socket.http")
  local body, code, headers, status = http.request("http://kong:8001/services/")
  return kong.response.exit(200, body)
end
 myfunction()

**Comment by Tieske** [comment]
You cannot use those libraries with Kong/OpenResty. They did blocking io, blocking the workers, as you experienced.

Try using the `lua-resty-http` library instead.
