### ISSUE TITLE
[Idea] Timer Based Processing Plugin

### ISSUE THREAD

**Issue by nijikokun** [Kong/kong-plugin-serverless-functions#2]
**Concept**

Periodically make request to proxy route where plugin is configured or periodically manually invoke a plugin configuration.

**Why?**

It is a core concept in serverless to have periodically ran functions.

**References**

- https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer
- https://docs.aws.amazon.com/lambda/latest/dg/with-scheduled-events.html

**Comment by Tieske** [comment]
have a look at: https://github.com/Kong/kong-plugins-system

**Comment by nijikokun** [comment]
We could actually add a `timer` config for functions enabled globally which makes them background processes and this would suffice as a solution.

**Comment by Tieske** [comment]
you can already do that using the upvalues PR (merged today) #13 

```lua
ngx.timer_at(0, function(premature)
   -- this runs as a timer
end)

return function() end --no-op for the request specific function
```

need to check though whether `timer_at` is available when the plugin is first loaded (nginx phase).

**Comment by nijikokun** [comment]
Ah, #13 might actually need to be reverted in that case. I misread the intention, I thought the upvalue was the returned function.

The implementation might cause existing functions to behave improperly

**Comment by Tieske** [comment]
I'm not following... why would existing implementations not behave properly?

**Comment by nijikokun** [comment]
Previously functions were invoked per request without being wrapped, now to service the same functionality you must wrap the functions in a function and return them. Otherwise it's immediately invoked, unless I am misunderstanding what is wrote in that PR

**Comment by Tieske** [comment]
no because it actually tests that. 

But thanks anyway for pointing it out, because that runtime test is flawed, and might execute the functions twice.

**Comment by Tieske** [comment]
fix here: https://github.com/Kong/kong-plugin-serverless-functions/pull/17

**Comment by Tieske** [comment]
fix here: https://github.com/Kong/kong-plugin-serverless-functions/pull/17
