### ISSUE TITLE
When adding a pre/post-function plugin, the function gets executed

### ISSUE THREAD

**Issue by EB123** [Kong/kong-plugin-serverless-functions#23]
I've also opened an [issue](https://github.com/Kong/kong/issues/5010) in Kong's repository, but I'm opening one here as well because I think it might be related to a recent issue that was done here.

So, as you can see in the issue I've opened in Kong, when trying to add a pre/post-function plugin in Kong 1.3, the function I want to add gets executed, which means that if I have something like this in my function:
```lua
if not custom_auth then
  return kong.response.exit(419, "This message is coming from the lua function itself!!!")
end
```
then the POST request to add the plugin gets a 419 status code with this custom message, and I'm unable to add the plugin.
This doesnt happen with Kong 1.0.3 & Kong 1.2

After digging up a bit, I think what's happening is that when Kong is validating the all the plugin's fields and get to the "config" field, it uses the custom_validator which contains the following [code](https://github.com/Kong/kong-plugin-serverless-functions/blob/2636b47cf59e9178335b7a697a40917d377c9d31/kong/plugins/pre-function/_schema.lua#L8):
```lua
local function validate_function(fun)
    local func1, err = loadstring(fun)
    if err then
      return false, "Error parsing " .. plugin_name .. ": " .. err
    end

    local success, func2 = pcall(func1)
```

Now, isn't this code actually executing the function i'm trying to add...?

Thanks! :smile:

**Comment by Tieske** [comment]
answered here: https://github.com/Kong/kong/issues/5010#issuecomment-529179184

**Comment by EB123** [comment]
@Tieske Thanks for the quick response! 

Following your answer in the other thread, is there a way that this issue can be prevented (without relying on the workaround you suggested)? I'm not (yet) familiar enough with all the Kong eco-system, but is there a way to run the function in some sort of "sandbox" so that the `kong` object won't be populated?

I mean, can't this be quite a risky side-effect? let's say I have in my function, that should be assigned only to a specific route, something like "if not condition, then do something destructive". Given that this condition will never be fulfilled when adding the plugin, then the destructive code will be executed.
