### ISSUE TITLE
readme doc link does not work

### ISSUE THREAD

**Issue by matti** [Kong/kong-plugin-serverless-functions#6]

**Comment by coopr** [comment]
https://github.com/Kong/kong-plugin-serverless-functions/pull/7

**Comment by matti** [comment]
hehe, still broken in master & issue closed.

**Comment by coopr** [comment]
Sorry, I'll leave this open until the PR gets merged.

**Comment by coopr** [comment]
Oh, it did get merged, and is now fixed in master - closing for real this time :)

**Comment by matti** [comment]
thx!
